### ISSUE TITLE
SDVX songs with non-western commas not importing from e-amusement CSV

### ISSUE THREAD

**Issue by Radipon** [TNG-dev/Tachi#861]
[score (1).csv](https://github.com/TNG-dev/Tachi/files/10663615/score.1.csv)

Scores for any of the umpty remixes of "Help me， ERINNNNNN!!" can't be imported.

Attempting to manually edit with escaped western commas or enclosing names in quotes didn't work either.

**Comment by zkldi** [comment]
something is wrong with the way this file is being uploaded. The source code only splits on western commas. perhaps the method of uploading the file is mangling the commas, somehow.

![image](https://user-images.githubusercontent.com/20380519/216993693-081143c7-5574-46a2-a495-b7244fec2c01.png)

For what it's worth: we can't use a "real" CSV parser for this situation because konami don't honor "real" CSV - they just split values on commas and don't honor quotes or anything like that.

*****

This import method -- with the exact input you have gave me -- works perfectly fine for me when I upload it. It is likely that something is wrong with your system or your locale, perhaps it is mangling the file somehow.

![image](https://user-images.githubusercontent.com/20380519/216994431-555e6411-f6cb-47e1-be30-c5d1d72d7848.png)

all of the imports you've tried that have failed have involved you editing the csv to change the name of the song. You shouldn't do that.

**Comment by zkldi** [comment]
regardless i've added support for quoting even in the naive CSV parse in a way that is safe. Thank you for the report.

**Comment by Radipon** [comment]
Thank you for updating that. As you stated, the were no errors when it's simply uploaded as is. I ran another import and from what I could see, there is only one offender in whatever konami's outputting for its CSV.

![image](https://user-images.githubusercontent.com/17075765/217105128-37defa6e-ab76-458c-a844-ab63212e826b.png)
