### ISSUE TITLE
Allow `#RANDOM` bms charts to be accepted by the IR

### ISSUE THREAD

**Issue by pfych** [TNG-dev/Tachi#893]
This topic has come up quite a bit in the discord and I feel like it's worth discussing here. 

Commonly discussion about `#RANDOM` begins with something along the lines of:

> bruh I got all hc in insane 1 but on the sites it says its 53 charts instead of 52

> like im on a quest to HC all of satellite i NEED to see that 100% completion on bokutachi once

It makes sense that people would want to have a visual "100%" completion against tables.

## The code

At an extremely high level glance the offending line of code is here: 

https://github.com/TNG-dev/Tachi/blob/740f2a374255d4282cc0bb0e20c5f6e39896b303/server/src/lib/score-import/import-types/ir/beatoraja/converter.ts#L152-L156

There are a few places that also mention `#RANDOM`

https://github.com/TNG-dev/Tachi/blob/740f2a374255d4282cc0bb0e20c5f6e39896b303/common/src/config/game-support/bms.ts#L172-L174

However it would be extremely short sighted to submit a PR with just that check removed.

## Potential issues

From my knowledge of the code base, if `#RANDOM` were to be accepted by the IR, the IR would _potentially_ need to know the users percentage clear. However, percentages when it relates to grade can create _fun_ edge cases since the grades are $x/9$ fractions.

I am not well versed in the front end code, so there also could potentially be a case where the charts max note count is expected to be a fixed value. However as mentioned bellow, scores submitted though the LR2 Hook seem to display perfectly fine.

### Open the floodgates (Easy)

Remove the `#RANDOM` check and inform users viewing these scores that the chart contains `#RANDOM` declarations and the data may be inaccurate.

### Only show the lamp (Hard)

When a score is submitted on a chart that contains `#RANDOM` we could show only the lamp, not the grade of the score. This however, could potentially be more effort than its worth as it'd likely require shimming existing score code.

### LR2 can submit random scores

I don't know enough about the LR Hook to comment on this, potentially a question for @MatVeiQaaa who writes and maintains the Bokutachi LR2 Hook. 

However there are a few scores that are viewable on Bokutachi and they don't seem to cause any obvious issues.

Example: https://bokutachi.xyz/games/bms/7K/songs/63259/CHART  
Example: https://bokutachi.xyz/games/bms/7K/songs/23264/CHART

### LR2IR & Mocha don't care, so why should we?

There's a lot that other IR's do that we don't do, and there's a lot that we do that they don't do. I don't believe it's a valuable add to the conversation by adding comments like these.

## In closing

I've opened this as an issue instead of a PR since I believe it's worth getting more input before opening a request to patch in a "feature" like this. I am happy to open a PR once we have discovered all potential unknowns and solved any issue related to this being patched in.

**Comment by MatVeiQaaa** [comment]
On the LR2Hook side of things, it is most likely possible to detect and flag charts which use #RANDOM. However, people would still be able to use older versions of the hook to submit such scores. There is a way to obsolete older versions, if endpoint would reject all scores that don't include "hasRandom" node in the request. Generally speaking it's possible, but it's a work for both Bokutachi, me, and significant annoyance for users on top of that, which deems the whole operation absolutely not worth it in my eyes. "Opening the floodgates" solution, however, seems absolutely reasonable to me. If anything, the scores are already there from LR2Hook, it's not gonna get more broken than it already is.

**Comment by MatVeiQaaa** [comment]
Besides LR2Hook, #RANDOM scores are also appearing on the Bokutachi through manual import of scores tool for LR2. And my theory is that it would be absolutely not possible for this tool to tell if the chart utilizes #RANDOM, as LR2 itself doesn't distinguish them from any others, thus never saves any data to indicate that.
LR2Hook could only tell that from a function call which #RANDOM invokes at runtime.

**Comment by pfych** [comment]
Potentially worst case scenario chart: https://bokutachi.xyz/games/bms/7K/songs/75445/CHART

https://www.youtube.com/watch?v=uzIv9Io-DS8

**Comment by zkldi** [comment]
> LR2IR & Mocha don't care, so why should we?

supporting `#RANDOM` is impossible to do correctly in a way that is satisfying for the end user. LR2IR and MochaIR get away with it by having *literally no useful features anyway* beyond displaying a song's scores in a table. 

Unresolvable problems:

- The notecount of the chart cannot be known.

We can't know the notecount of the chart anymore as it is potentially different for all users. This creates a series of bastard, more confusing edge cases, like `MAX-10` being better than `MAX-11`, and `3900` ex score being significantly worse than `130`.

- Anything about the chart cannot be known.

Because `#RANDOM` is merely a preprocessor instruction (go look at how raja/lr2 parse it), *anything* in the entire chart file can be `#RANDOM`. this includes making the song title, song artist, parsability, etc. be completely nondeterministic. As such, we could not know without semantic analysis whether any of the metadata we recieve is "correct".

(n.b. the way beatoraja handles this is by co-incidence; the parser itself runs the `#RANDOM` preprocessor instructions so the actual game *never even makes a decision*. The data it caches about the chart is completely nondeterministic.)

In many ways, this *directly breaks* the ability to trust the checksum of a chart.

> Potentially worst case scenario chart:

The worst case scenario chart is whatever you want it to be given that anyone can make a bms file using notepad. For a community-ran game the idea of pointing to a specific worst case is silly. Here's an amusing case:

```
#RANDOM 1000
#IF 1
    <put some really easy chart for gengaozo here>
#ELSE
    <put freedom dive four dimensions here>
```

how can you say anything with any confidence about this chart?

> LR2 can submit random scores

This is a bokutachi bug. Charts with `#RANDOM` should never have been on the IR in the first place. this is a longstanding bug that I haven't bothered to fix and isn't the problem of the lr2hook or any other service. We only accept new charts from the beatoraja IR submissions, and those are correctly handled.

> Commonly discussion about #RANDOM begins with something along the lines of:
>    bruh I got all hc in insane 1 but on the sites it says its 53 charts instead of 
>    like im on a quest to HC all of satellite i NEED to see that 100% completion on bokutachi once
> It makes sense that people would want to have a visual "100%" completion against tables.

The actual problem you're discussing is that charts with `#RANDOM` are still available on the site. Given that this is a bug, fixing this will fix all of the end-user facing problems. At most, the concern would be "Why isn't this folder the right size?" and the answer is intuitive.

**Comment by zkldi** [comment]
the short of it is that being able to know and pin a charts notecount is *extremely* convenient for the end user (and for the codebase) whether the user realizes it or not. It is much more intuitive that a score with `X + 1` exscore is better than `X` for all X.

`#RANDOM` support will never be added. The bug with lingering `#RANDOM` charts in bokutachi is a long one, and should've been fixed a while back.

**Comment by pfych** [comment]
Thanks for the quick follow up, however I do think closing the issue without  discussion was to quick of a decision.

> We can't know the notecount of the chart anymore as it is potentially different for all users. This creates a series of bastard, more confusing edge cases, like MAX-10 being better than MAX-11, and 3900 ex score being significantly worse than 130.

I feel like again, this is something that is a non-issue when it comes to BMS. Charts that have this potential edge case are likely high level charts where players are aware of the charts quirks. With a brief discussion in the BMS channel + BMS Server most people use GBATTLE anyway and play against a known good play.

> how can you say anything with any confidence about this chart?

I think using this worst case is an extreme that would never make it onto a table that is currently supported by the site. **Could possibly, we make exceptions for charts that are in tables the site supports?**

**Comment by zkldi** [comment]
If we make acceptions it means we need some sort of chart upload and manual review process. Technically, the seeds has that.

The correct way to move forward with specifically added `#RANDOM` support is to change the beatoraja IR logic to search for the chart on the IR first, only rejecting the score if it has RANDOM *AND* isn't already on the IR.

Then, using the existing seeds review process to have people manually add #RANDOM charts that can be checked to have insignificant[1] `#RANDOM` usage.

This process could be automated by scripts.

[1]:
**MUST NOT** make the parsing of the following fields non-determinstic:
`#ARTIST, #TITLE, #SUBTITLE, #SUBARTIST` and `notecount`.

*****

A more lr2ir/mochair and more annoying way to move forward would to be making `percent` a provided metric for a score, so that all score submission methods must submit a 3-tuple of `(score, percent, lamp)`.

This means we can derive the notecount and then we have to tag every uploaded chart as to whether it was `#RANDOM` or not to know the soundness of the input we got (we could make `notecount` nullable for "unknowable" notecount, etc.)

*****

However, I fundamentally disagree with the idea of adding this support. I don't want to have to deal with the idea of an "unknowable" notecount.
It's fucking stupid, it's confusing for end users, it punches a huge hole in the soundness of score data if unchecked and it is a silly gimmick that really has no place in "table play" in the first place.

The fix I think should be done is removing all existing `#RANDOM` charts from the site, and putting a warning on every bms folder that we don't accept those charts and as such the size of the folder might not correspond with the size in game.

I closed this issue because I think the problem at hand is something completely different (charts with `#RANDOM` *are* already on the site and confuse users). I can leave it open if you think there's still discussion to be had.

**Comment by pfych** [comment]
I agree that opening the floodgates is a nightmare, and that percent causes more issues than it solves.

Your replies are exactly why I opened a ticket instead of submitting a PR with the check removed because this is definitely a pain point for end users & developers. (We need a better BMS client :sob:)

However, if removing all charts that include `#RANDOM` is a task in the future, would, while implementing that; also implementing a whitelist for any charts that are tabled be a potential feature that could be also implemented? The number of charts that would make it through this whitelist would likely be an insanely small number <10.

Fully lamped insane being a good example of how minor the issue is:
![image](https://user-images.githubusercontent.com/11114594/230343609-797f4e72-fe8c-4a89-80e7-7a4477235fb1.png)

> I closed this issue because I think the problem at hand is something completely different (charts with #RANDOM are already on the site and confuse users). I can leave it open if you think there's still discussion to be had.

I think approaching the issue from "Allow `#RANDOM`" instead of "Hide `#RANDOM` charts from folder view" is overall more productive and makes pinpointing the exact work that needs to be potentially done easier. Since one is narrowing down what `#RANDOM` charts are "ok" whereas the other one is what charts include `#RANDOM`.

**Comment by pfych** [comment]
It is worth keeping this `#RANDOM` stuff in mind since I think it's the last real friction point for end users who play BMS on Bokutachi.

**Comment by zkldi** [comment]
> I think approaching the issue from "Allow #RANDOM" instead of "Hide #RANDOM charts from folder view" is overall more productive and makes pinpointing the exact work that needs to be potentially done easier.

It's not more productive. "Allow #RANDOM" is not going to happen. it is a *significant* jump in complexity for *no* gain.

People do not actually want `#RANDOM` charts to be tracked by bokutachi (even if they say they do), what they *actually* want is to be able to fill out their tables/folders.

The actual concept of "track my score on an unknowable chart" is *complete nonsense* and will never be supported.

>  Since one is narrowing down what #RANDOM charts are "ok" whereas the other one is what charts include #RANDOM.

It's not the case of hiding them from folder view: it's removing them completely from the site. They never should've been there in the first place. This is a bug and should be fixed tonight.

Knowing what random charts are "ok" is even less useful than I initially thought, the charts in the insane table that have `#RANDOM` declarations affect the notes. They're not deterministic to play and - even though in the obvious examples it's minor - it's not something we can support *for all* charts.

It's important to note that the reason this is so much of a problem is because of these two things *together*. on their own, either is fine:
- A chart is ran through a random preprocessor before evaluation
- Users can submit any chart to the IR, and that only shows us `evaluated_info(chart)`.

These two things are not mutually satisfiable in a way that doesn't completely break the IR for malicious/contrived/gimmick BMS charts.

I already happen to know the md5 of every chart on Tachi with `#RANDOM` declarations, because they're all in the same dataset I initialised Bokutachi with, so it's no additional work on my part.

> it's the last real friction point

It is, but the friction here is that you can't fill out your table/folder because of broken charts. Nobody actually cares about `#RANDOM` support, it's just a blocker for something else they're doing. The actual solution here is to remove these charts.

**Comment by zkldi** [comment]
All #RANDOM charts have been removed from the site.
